# Generated by Django 5.1.3 on 2024-12-02 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='days_working',
            field=models.CharField(default=23, max_length=255),
            preserve_default=False,
        ),
    ]
